---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: bank
spec:
  containers: 
    - name: cont1
      image: httpd
      ports:
        - containerPort: 80
      resources:
        request:
          cpu: "50m"
          memory: "5Mi"
        limits:
          cpu: "100m"
          memory: "10Mi"
